title: vScheduler
description: A flexible playlist builder for vMix
show_downloads: true
github:
  repository_name: vScheduler
  zip_url: https://github.com/237domingo/vScheduler/releases/download/v1.1.4-alpha.2/vScheduler.v1.1.4-debug.2+buiddate260821.zip
theme: jekyll-theme-leap-day
