title: vScheduler for vMix
description: A flexible playlist builder for vMix
show_downloads: true
github:
  repository_name: vScheduler for vMix
  zip_url: https://github.com/237domingo/vScheduler/releases/download/v1.1.4-alpha.3/vScheduler.v1.1.4-alpha.3+builddate300821.zip
theme: jekyll-theme-leap-day
